# version: '3'
# services:
#   nginx: 
#     image: nginx:alpine
#     container_name: nginx_container
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     ports:
#       - 80:80
#       - 443:443

#   go:
#     image: golang:alpine
#     container_name: go_container
#     volumes:
#       - ./go-src:/home
#     command: 
#     expose:
#       - "8002"
version: '3'
services:
  gosrv:
    build:
      context: ./go-base
    expose:
      - "8002"
  nginx:
    build:
      context: ./nginx-base
    ports:
      - "80:80"